### ISSUE TITLE
WCO Phase Reset

### ISSUE THREAD

**Issue by Nowhk** [Edge-Modules/Edge#3]
Is it possible to reset the phase of the WCO osc? I link it to an ADSR, and I want (once I play a new note), to restart the signal at phase 0.

**Comment by Edge-Modules** [comment]
It's actually possible in 'LFO' mode. You ave to send a trigger or gate at the FM Input to reset  the phase.

**Comment by Nowhk** [comment]
Yes, but I'm using it generating audio (i.e. as synth) signal, not as modulation source. 
Could you add a dedicated input trig for both audio and lfo, couldn't?

**Comment by Edge-Modules** [comment]
I can try to make this next week.

**Comment by Nowhk** [comment]
Wow, thanks ;) I'll waiting this, awesome.

**Comment by Edge-Modules** [comment]
On what system are you Nowhk?

**Comment by Nowhk** [comment]
I'm on Windows

**Comment by Edge-Modules** [comment]
nice, i m updating the WCO right now and the only release i can actually do is for windows :D

**Comment by Edge-Modules** [comment]
Just tell me if this is what you wanted ;) so i can close this issue ^^

**Comment by Nowhk** [comment]
Haha awesome! I was lucky ;) Tomorrow I'll check It out ;) 
Are you the man from Dove Audio? Or simply inspired from it?

**Comment by Edge-Modules** [comment]
i m not from dove audio; i ve never touched a modular ^^

**Comment by Edge-Modules** [comment]
But i make music since 20 years and i was just amazed by the possibilities of VCV so i tried to make modules. And Actually, i love that ! :D

**Comment by Nowhk** [comment]
Can you propagate it on plugin manager? Can't see it for update...

**Comment by Nowhk** [comment]
Hello? Or give me the zip :)

**Comment by Edge-Modules** [comment]
Hi, the zip is in the release since yesterday, for windows only

**Comment by Edge-Modules** [comment]
So di you try, was it what you wanted?

**Comment by Nowhk** [comment]
Tried now! Yeah it seems to works like a charm! Thank you very much! Nice feature

**Comment by Edge-Modules** [comment]
:D

Haaa nice !
Have fun ! If you have any other suggestion, open an issue ! I close that one.

Bye Nowhk ;)
