### ISSUE TITLE
Sometimes waves not loaded in VVCO

### ISSUE THREAD

**Issue by Petervos2018** [Edge-Modules/Edge#5]
As seen here : 
https://youtu.be/_4UYF0fbMyE?t=3134

**Comment by Edge-Modules** [comment]
hi Petervos :)

This is corrected  on the 0.6.5, i have uploaded sources yesterday but it's actually not up to date on vcv plugin manager.  
https://github.com/Edge-Modules/Edge/releases/tag/0.6.5

Thank you for the feedback ;)

**Comment by Petervos2018** [comment]
Thank you for your answer Mr. Edge :)

And thank you for your great modules,

Greetings Peter.

**Comment by Edge-Modules** [comment]
;) Have fun !
