### ISSUE TITLE
Is it possible to output LFO signal normalized and in -5/5v?

### ISSUE THREAD

**Issue by Nowhk** [Edge-Modules/Edge#6]
I'd like to understand if its possible to output signal normalized (in LFO mode), and in the range -5/5v.

Wavetables doesn't reach -1/1 values, so the output its never normalized.
Also, mod between -5/5 without any intermediate scale would be good (or at least, output in 0/10 range).

Why 0/5?

Thanks

**Comment by Edge-Modules** [comment]
Normalisation on Wavetables with morphable transitions seems impossible to me; without morphing, it only depends on the wavetable you use. The range 0/5 is for the possibility to use the WCO in lfo mode as a triggered enveloppe.  I can implement a uni/bi -polar button for the next version. And if you have an idea on how to normalize morphing wavetables, i m open to any suggestion ;)

Just to know, why do you need normalisation on Lfo?

**Comment by Nowhk** [comment]
I meant "starting" with normalized waveform. For example, select sine wave, and output it: it never reach the max peaks, because its already lower in volume. So a sort of normalization considering all waves you load.

Also, a gain knob in the output would be nice, so in any case I can rescale the output volume.

I need normalization because, for example, it never reach -5 to 5 when modulating, always lower values...

**Comment by Edge-Modules** [comment]
I understand what you ask but again, it would be a lack of performance considering i would have to normalize on each modification of the width or morph on the wavetable. You can easily put a 'Befaco a*b+c' for exemple to manage the range of the output, like on any VCOs ( wich are almost never normalised btw ). I hope it would help.

**Comment by Edge-Modules** [comment]
Ok so here is what i ve done ->
You will now have the choice of the LFO Range from -5 / 5 V to 0 / 10 V via the right click menu.
There is the possibility to auto-scale the output but you will have   -5% of performance on the module when activated.

**Comment by Edge-Modules** [comment]
This will be avalaible on the next update.

**Comment by Nowhk** [comment]
Thanks man! I'll check it out
