### ISSUE TITLE
vcv 1.0 compatibility

### ISSUE THREAD

**Issue by stephanepericat** [Edge-Modules/Edge#8]
Hi,

I use WCO a lot, and was wondering if you have any plans to update these plugins to 1.0 ? :)

Regards,
Stefan

**Comment by Edge-Modules** [comment]
Hi stephane,

Compatibility for rack V1.0 is done; i must work on polyphony now :)
Have fun !

**Comment by stephanepericat** [comment]
awesome :D thanks for the quick turnaround!

**Comment by Edge-Modules** [comment]
My pleasure !Tell me if you got any issue ;)
