### ISSUE TITLE
Update to latest version of VCV?

### ISSUE THREAD

**Issue by pgatt** [Edge-Modules/Edge#9]
Hi there, I'm just wondering whether you will update your fantastic modules for the latest version VCV Rack?

**Comment by Edge-Modules** [comment]
Hi , they re actually updated on Github for V1 compatibility but not on the plugin manager. I d like to make WCO polyphonic before updating it in the plugin manager.

**Comment by pgatt** [comment]
Cool, great to know!

**Comment by Miserlou** [comment]
So good! I'm missing WCO so much, amazing that it'll be poly!
